### ISSUE TITLE
Mojave Availability ALC887

### ISSUE THREAD

**Issue by sdesign** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13#10]
Hello, will you have mojave on this availability?
Thank you, happy holidays!

**Comment by sdesign** [comment]
Yes, please. I would gladly test it.

**Comment by insanelydeepak** [comment]
try this 
use layout 14 
[cloverHDA 887 10.14.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2706633/cloverHDA.887.10.14.zip)

**Comment by sdesign** [comment]
Working as expected. Thank you!

**Comment by insanelydeepak** [comment]
great will push repo soon 

enjoy good sound
