### ISSUE TITLE
ALC662 Not working

### ISSUE THREAD

**Issue by joki0924** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13#11]
My audio device is ALC662 and it's not working.
I tried almost everything.
Please help me.
Thanks.

**Comment by joki0924** [comment]
This is my EFI.
[EFI.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2739676/EFI.zip)

**Comment by insanelydeepak** [comment]
Hi 
remove HDEnabler and use this config.plist 
[config.plist.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2741339/config.plist.zip)


after restart send me trouble shoot files 
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/TroubleShoot/Troubleshoot%20Reporting.md

**Comment by joki0924** [comment]
Thanks for reply.
I will try right now.

**Comment by joki0924** [comment]
Well.. above config.plist never works on my computer.
I changed my plist file to above one, restarted my computer, and it showed me white ban icon and never boot up.
I had a backup of plist file, so i used my usb stick to recover my plist file.

What can be reason for my audio?
Can you please help me?
Thanks.

**Comment by insanelydeepak** [comment]
> Well.. above config.plist never works on my computer.

what it means , it won't boot ? 

> What can be reason for my audio?

let me debug 

> Can you please help me?

sure , im happy to help 

send me debug file 
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/TroubleShoot/Troubleshoot%20Reporting.md

**Comment by joki0924** [comment]
Thanks for your kind reply.
but what is IORegistry ?

**Comment by insanelydeepak** [comment]
use this one will collect all files i needed 
https://github.com/black-dragon74/OSX-Debug

**Comment by joki0924** [comment]
thanks.
i will try

**Comment by joki0924** [comment]
![screen shot 2019-01-11 at 1 38 25 am](https://user-images.githubusercontent.com/30487501/50986355-99dd8580-1541-11e9-85cd-3424c6c34195.png)
i was trying this ....

**Comment by insanelydeepak** [comment]
yes this is same just you need to save as and that file is enough 

but that tool is really good and have all additional files which i may ask you later , it will save time

**Comment by joki0924** [comment]
yeah i already downloaded that repo.

**Comment by joki0924** [comment]
[sandy’s iMac.ioreg.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2746474/sandy.s.iMac.ioreg.zip)
anyway this is iorg file.

**Comment by joki0924** [comment]
I tried above repository..
![screen shot 2019-01-11 at 1 44 06 am](https://user-images.githubusercontent.com/30487501/50986689-6fd89300-1542-11e9-9523-a469713faa98.png)

**Comment by joki0924** [comment]
Hi.
I think I finished what you want.
[debug_20469.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2746521/debug_20469.zip)
```

=====================================
+   macOS DEBUG REPORT GENERATOR    +
-------------------------------------
+       SCRIPT VERSION 4.3.3        +
=====================================
 
=====================================
+      AUTHOR: black.dragon74       +
=====================================
 
Found script data directory at /Users/sandy/Library/debugNk
EFI Mount Script (RehabMan) found. No need to download.
IORegistryExplorer found at /Applications/IORegistryExplorer.app
Verifying if correct version of IORegistryExplorer is installed.
Your version of IORegistryExplorer.app passed the check. Good to go!
Patchmatic not installed. Checking in DATA directory.
Binary found in DATA directory.
Data will be dumped at /Users/sandy/Desktop/20469
Password:
Dumping loaded ACPI tables.
Dumped loaded ACPI tables.
Dumping clover files.
Mounted EFI at /Volumes/EFI (credits RehabMan)
Verifying your EFI files...
ACPI files were dumped recently. Great!
Preboot log was dumped recently. Great!
All checks passed. Copying CLOVER files...
Removing theme dir from the dump.
Removing tools dir from the dump.
Masking your System IDs
Dump of CLOVER files completed successfully.
Unmounted /Volumes/EFI
Dumping System log.
Dumping kernel panic logs...
Dumping kernel log.
Dumping kextstat.
Dumping kextcache
Dumping IOREG.




^CHey, you pressed Ctrl+C. Quit?[yY/nN]: 
Ah! Okay. Continuing then..
IOREG dump failed. Retrying by increasing delays...


Increased delay by x2 times. Retrying...
sandys_iMac^[[D^[[C^[[C^[[C^[[C
^CHey, you pressed Ctrl+C. Quit?[yY/nN]: n
Ah! Okay. Continuing then..
IOREG dump failed. Retrying by increasing delays...
Increased delay by x3 times. Retrying...
IOREG Verified as /Users/sandy/Desktop/20469/sandys_iMac.ioreg
System dump not requested.
You may use gen_debug -sysprofile to generate system dump.
For output in TXT format use: "gen_debug -sysprofile txt". Default format is SPX
Dumping Boot log
Dumping NVRAM values...
Zipping all the files
Zipped files at: /Users/sandy/Desktop/20469/debug_20469.zip
Dump complete. Open /Users/sandy/Desktop/20469?(Yy/Nn) y
Thank You! Hope your problem gets sorted out soon.
sandys-iMac:~ sandy$ 
```


IORegistryExplorer was launched but it showed me some trust dialog.
So i had to try again.
At that time I understood why it says never touch computer at the beginning haha~.

**Comment by joki0924** [comment]
Should I add Kext patch as the readme file?

**Comment by joki0924** [comment]
okay i will try.

**Comment by joki0924** [comment]
I applied patch and didn't work.
Here is my another debug file.
[debug_17301.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2750261/debug_17301.zip)

**Comment by joki0924** [comment]
May I have your Skype contact ?
I sent some message to your gmail account via hangout but I had no reply. seems like you never use it.
Thanks.

**Comment by insanelydeepak** [comment]
remove cloverHDA and disable patches and install this kext and reboot 



[AppleHDA-280.12-ALC662.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2750313/AppleHDA-280.12-ALC662.zip)

**Comment by joki0924** [comment]
okay
I will try.

**Comment by insanelydeepak** [comment]
> May I have your Skype contact ?
only available through mailbox and other forum insanelymac and osxlatitude

**Comment by joki0924** [comment]
hmm okay no problem.

**Comment by joki0924** [comment]
i hope we can keep contact via here.
I am very glad to meet you an awesome guy.

**Comment by joki0924** [comment]
Should I remove current AppleHDA?

**Comment by insanelydeepak** [comment]
don't worry i reply as fast i could in inbox and also you can use insanelydeepak@gmail.com

**Comment by insanelydeepak** [comment]
no , just use kextutility and drag kext on app

**Comment by joki0924** [comment]
Should I remove current AppleHDA?
I already have applehda.kext in my /System/Library/Extensions

**Comment by joki0924** [comment]
okay
I will try with KextUtility

**Comment by joki0924** [comment]
Here is my current debug info
[debug_19508.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2750384/debug_19508.zip)

Please have a look.
Thanks.

**Comment by insanelydeepak** [comment]
[AppleHDA-280.12-ALC662.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2751680/AppleHDA-280.12-ALC662.zip)

try this one , if it doesn't send me codec_dump

**Comment by joki0924** [comment]
I tried above one.
It does not work :(

**Comment by joki0924** [comment]
This is my current info.
[debug_2180.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2751740/debug_2180.zip)

**Comment by joki0924** [comment]
Please have a loook. Thanks for your efforts.

**Comment by insanelydeepak** [comment]
provide me codec_dump

**Comment by joki0924** [comment]
Hi.
Thanks for your efforts and kind help until now.
I finally fixed up my audio.
I removed AppleHDA and installed VoodooHDA 2.8.2 and my sound works fine.
:) Thanks again.
We may close this issue.

**Comment by insanelydeepak** [comment]
voodoo is good but you can try AppleALC too , it looks your codec needs special patch, i need codec_dump to make exact patch according your system 


feel free to re-open if you need it 

Good luck !

**Comment by joki0924** [comment]
If I can help you by giving my codec_dump to you, I will surely help.
But I am not sure how to make "codec_dump".

**Comment by insanelydeepak** [comment]
just you need linux live usb and below command 

` 1. Use Ubuntu or Any Version of Linux Distro (Note : Use the latest version of Linux and Alsa drivers )
 2. Open Terminal and copy paste below Code :
  cd ~/Desktop && mkdir CodecDump && for c in /proc/asound/card*/codec#*; do f="${c/\/*card/card}"; cat "$c" > CodecDump/${f//\//-}.txt; done && zip -r CodecDump.zip CodecDump
  
 3. On Desktop there’s a folder/file name Codec_dump
 4. Save this to safe place  `


all is here , just read it how to get codec_dump

**Comment by joki0924** [comment]
Sorry. I don't have any ubuntu ..

**Comment by joki0924** [comment]
Can I do it on macos ?

**Comment by joki0924** [comment]
Or windows?

**Comment by joki0924** [comment]
Sorry for late reply. I had to move my house. took much time.
How can I do "make live usb of linux" ? can you give me link to some tutorial ?
