### ISSUE TITLE
ALC236 (from dell vostro 3578) audio can't work

### ISSUE THREAD

**Issue by applehacktosh** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13#12]
BHAI HELP KRO PLEASE 

Codec: Realtek ALC236
Address: 0
Vendor Id: 0x10EC0236
audio is not working at all please help
i gott the vanila from here  https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/tree/master/Vanilla AppleHDA didnt work 

 i also try HDA PATCHER to patch virgin applehda kext  1.9 APPLEHDA NOT WORK ALSO tried

also tried put lilu codecomander with applealc stil not work

also tried this layour layout 3, 11, 13, 15 still not work also did reset HDA IN CLOVER STILL NOT WORK 

 bro your expert advice and help needed this mystery is not getting solved

**Comment by insanelydeepak** [comment]
Hi 
provide codec_dump and i don't have this codec in my repo 

`BHAI HELP KRO PLEASE`

pareshan mat ho fix krte hai ise , codec_dump send kro and config.plist bhi sath mein

**Comment by applehacktosh** [comment]
[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2759822/Archive.zip)
plist with codec @insanelydeepak voodooHDA usa krra hu abi lekin use headphones nhi chal rhe

**Comment by insanelydeepak** [comment]
feel free to reopen when you available
