### ISSUE TITLE
ALC295 Issue - Only Bottom Speakers Working - HP Spectre x360 Kaby Lake (2017)

### ISSUE THREAD

**Issue by lolitsgab** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13#2]
--------------------
This issue was posted in the 10.12 fork. It has been transferred here as this is the correct section.
--------------------
[troubleshoot.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2187108/troubleshoot.zip)

My machine is the[ HP Spectre X360 Kaby Lake 2017 model](https://support.hp.com/us-en/product/hp-spectre-13-ac000-x360-convertible-pc/14039877/manuals) dual-booting windows 10 and OS X 10.13.6
Bang & Olufsen Audio (ALC295)

The issue is that only the secondary speakers that are located on the bottom of the computer work. The top (main) speakers (located on top of the keyboard)  do not work or output any sound. I have attached the IOREGExplorer output, my clover config file, my kextstat | grep -y AppleHDA output, and  a screen shot of the system profiler for my audio hardware.

I would be very thankful if you could help me out with this @insanelydeepak 

Here is my jarvis Codec Dump.
[jarvis.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2230471/jarvis.zip)

I can get the linux if necessary, but it'll be in a few days as my friend has my USB only USB drive :(

Thank you!

**Comment by lolitsgab** [comment]
Just wanted to check up if you needed any additional information! Thanks!

**Comment by insanelydeepak** [comment]
Hi 
send me codec_dumpt oo

**Comment by insanelydeepak** [comment]
Hi 
meanwhile can you try ? 
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/blob/master/Laptop/ALC295:3254.zip

https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/blob/master/Laptop/ALC295_v2%20Asus%20UX430UA.zip

**Comment by insanelydeepak** [comment]
Hi 
guys are you available to fix this issue ? feel free to re-open issue if anyone interested
