### ISSUE TITLE
No audio from laptop

### ISSUE THREAD

**Issue by Terminalstrip** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13#4]
Hi, I've tried your files but they do not work. I see the integrated sound card but it does not sound, I have a subsystem different from all the others. can you help me?
I have already tried to install CodecCommander but it does not work
All the requested files are in the attacched
[Trouble.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2372857/Trouble.zip)

**Comment by insanelydeepak** [comment]
Hi 
did you tried ALC269VB in this repo ? 

before attempt you must remove AppleALC and use Layout13 in config.plist

**Comment by insanelydeepak** [comment]
Hi 
are you available to fix this isssue ? if yes then re-open issue
