### ISSUE TITLE
Request : Please add original AppleHDA.kext to repo

### ISSUE THREAD

**Issue by YoussF** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13#5]
Hello,

It will to nice to have the original AppleHDA.kext to this repo. Like [here](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/tree/master/Vanilla%20AppleHDA%20). I accidentally deleted my original file and since it is a prerequisite for cloverHDA i can't use it.

Thank you very much for your help.

Y.

**Comment by insanelydeepak** [comment]
done , check new commit

**Comment by YoussF** [comment]
Thank you !
