### ISSUE TITLE
could you help me to make a 10.14 version of alc298  

### ISSUE THREAD

**Issue by Summer-Arrival** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13#7]
I used to make a 10.13 version, https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/issues/47, but I have no idea how to build the latest version. Thanks you!

**Comment by Summer-Arrival** [comment]
fixed it up! (with alcplugfix and latest applealc)

**Comment by insanelydeepak** [comment]
enjoy good sound
