### ISSUE TITLE
Request: ALC256

### ISSUE THREAD

**Issue by htpcrig** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13#8]
ALC256
Audio Device: 0x80869D71
Sub Device:    0x10251269
Codec ID:        0x10EC0256
Revision:          0x0002

Note: Your current ALC256 ComboJack works but with issues.
* Mic is not working. Internal Mic is detected as Line-In sometimes. 
* The Headphones becomes distorted after a 20 seconds from restart or frest start.

What info should i send for you to debug this @insanelydeepak 

Thank You :)

**Comment by htpcrig** [comment]
Hi insanelyDeepak

here is my codec_dum from latest Ubuntu.
[codec_dump.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2568983/codec_dump.txt)

Note: I have googled one of the post of Mirone about Microphone not listed in codec_dump of ALC256. But he managed to work it out. Sadly, his ALC256 didnt work on me ( Speaker no sound, Mic no sound. HEadphone works though with commandcommander)

**Comment by insanelydeepak** [comment]
try this layout 13 

[ALC256 v1.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2593053/ALC256.v1.zip)
[ALC256 v2.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2593054/ALC256.v2.zip)

**Comment by insanelydeepak** [comment]
also provide me dmesg output from linux

**Comment by htpcrig** [comment]
Hi insanelydeepak
i will test when i get home and report. tomorrow i will be free also,  so we can test the whole day :D

Thanks!

**Comment by htpcrig** [comment]
hi isanelydeepak
i have tested both attachement. both didnt work. cant detect sound in system pref

**Comment by htpcrig** [comment]
can this be moved in 10.12, because we are testing it for sierra?

**Comment by insanelydeepak** [comment]
sure 

will you provide dmesg output from linux ?

**Comment by htpcrig** [comment]
i will once i get the mic working in linux. its not working by default. its a know issue for acer swift. im trying the workaround atm.

**Comment by insanelydeepak** [comment]
i found your codec_dump don't have mic nodes , thats why i asked dmesg output so i can check how linux is doing

**Comment by htpcrig** [comment]
oh i didnt get you hahha... ok here is dmesg from linux :)
[htpcrig_dmesg_linux.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/files/2598764/htpcrig_dmesg_linux.txt)

**Comment by insanelydeepak** [comment]
> oh i didnt get you hahha... 

i mean codec_dump clearly shows that mic isn't working in linux

is your microphone working ??

**Comment by insanelydeepak** [comment]
is your mic working in windows ??

**Comment by htpcrig** [comment]
Hi insanelydeepak
Great! Yes, mic is working in windows. 
Whats your plan?

**Comment by htpcrig** [comment]
Hi insanelydeepak
I am currently still at work.. il be home this weekend.
Thank you

**Comment by insanelydeepak** [comment]
> When you see Line-In in Sound->Input then It probably means the input is switched to external mic
> If you cannot use external mic(no volume control etc.), then you may be using a wrong configdata
> So which layout-id are you using?

actually he has some different issue his neither codec_dump don't have nodes for Mic(Int) and Mic (Ext as Line-In) nor linux

**Comment by htpcrig** [comment]
Hi @insanelydeepak
It has been over a month since my last post. Sorry for that.
I found a linux link regarding this issue. I guess i just have to wait till they solved it, so i can give you a new dump that includes a mic.
https://forums.linuxmint.com/viewtopic.php?f=49&t=279424&p=1576319#p1576319

For the meantime, i will close this issue.

Thank you so much for the time you have shared :)
